/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7noNTPqwCxV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-background">
      <Card className="w-full max-w-2xl p-8">
        <CardHeader>
          <CardTitle>Certificate Generator</CardTitle>
          <CardDescription>Create a custom certificate for your recipient.</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-6">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="recipient-name">Recipient Name</Label>
              <Input id="recipient-name" placeholder="Enter recipient's name" />
            </div>
            <div className="space-y-2">
              <Label htmlFor="certificate-title">Certificate Title</Label>
              <Input id="certificate-title" placeholder="Enter certificate title" />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="message">Message</Label>
            <Textarea id="message" placeholder="Enter a message" rows={4} />
          </div>
          <div className="flex justify-end">
            <Button type="submit">Generate Certificate</Button>
          </div>
        </CardContent>
      </Card>
      <div className="mt-8 w-full max-w-2xl">
        <div className="bg-white border border-gray-200 rounded-lg shadow-md p-8">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-4">
              <img
                src="/placeholder.svg"
                alt="Logo"
                width={50}
                height={50}
                className="rounded-full"
                style={{ aspectRatio: "50/50", objectFit: "cover" }}
              />
              <h2 className="text-2xl font-bold">Certificate of Achievement</h2>
            </div>
            <div className="text-right">
              <p className="text-sm text-muted-foreground">Awarded to</p>
              <h3 className="text-2xl font-bold">John Doe</h3>
            </div>
          </div>
          <p className="text-lg mb-4">In recognition of your outstanding contribution and dedication.</p>
          <div className="border-t border-gray-200 pt-4 text-center">
            <p className="text-sm text-muted-foreground">Presented on {new Date().toLocaleDateString()}</p>
          </div>
        </div>
      </div>
      <div className="mt-8">
        <Button variant="outline">Download Certificate</Button>
      </div>
    </div>
  )
}
